### PR TITLE
"Skip playlist without tracks when performing 'Export All' action"

### PR DESCRIPTION
**Pull request by htaunay**
Some special playlists, e.g. Starred, don't offer track info, and
therefore cannot be exported. These should be skipped when attemtping
to export all of a given user's playlists.

### CODE REVIEW

**Comment by pavelkomarov** [comment]
Can we merge this, since it's passing the tests?

**Comment by htaunay** [comment]
Mainly trying to work around the "Export all" button failing due to

**Comment by pavelkomarov** [comment]
Export all works in my version. Go use it instead.

**Comment by htaunay** [comment]
Please ignore my comment above, turns out it just took a few mins. Thanks for this work!

**Comment by pavelkomarov** [comment]
Watsonbox didn't do any rate limiting, so it immediately fails if you have large or many playlists.

**Pull request closed without merging**
